function renderGUI () {
    let wrapper = document.getElementById("wrapper");
    wrapper.innerHTML = `
    <div id="backgroundContainer">
        <h1 id="titleText">RAVE LINQ</h1>
        <div id="contentContainer">
            <div id="infoBox">
                <h2>ARE YOU A DJ?</h2>
                <img id="ravePic" src="./media/images/ravePic.png">
                <p id="descriptionP">Here you can explore managers through powerful data visualizations that show exactly how they perform when it comes to income, audience demographics and where their artists are performing. Compare managers based on what matters most to you, and find the right fit with clarity and confidence.</p>
            </div>
            <div id="dividerBox">CONTINUE TO COMPARE MANAGERS</div>
            <div id="visualizationContainer">
                <h3 class="category">DJ Income Overview</h3>
                <p class="description">See the average yearly income generated by each manager’s DJs, adjusted for both the number of DJs they manage and how long they’ve been active.
                The result shows how much income, on average, each DJ under a manager brings in per one year.</p>
                <div id="firstViz"></div>
                <p class="description" id="belowText">This line chart displays the average yearly income of DJs represented by various managers between 2015 and 2024. Each line corresponds to a different manager, showing income trends over time. Use the filter functionality to highlight one or more managers and compare how their DJs’ average incomes has evolved throughout the years.</p>
                <div id="secondViz"></div>
                <div id="buttonContainer"></div>
                <h3 class="category" id="annualGigText">Annual Gig Distribution</h3>
                <p class="description">Explore how active each manager has been in securing gigs for their DJs over the years. This heatmap uses color to reflect intensity: dark green signals high activity, light green indicates low activity, while lighter shades show moderate levels. Hover over a cell to see the average number of gigs per DJ for that year.</p>
                 <div id="legendBox">
                    <div id="legendOne">
                        <p class="legendP">Very few<br>0-13</p>
                        <div id="legendColorOne"></div>
                    </div>
                    <div id="legendTwo">
                        <p class="legendP">Few<br>14-26</p>
                        <div id="legendColorTwo"></div>
                    </div>
                    <div id="legendThree">
                        <p class="legendP">Many<br>15-39</p>
                        <div id="legendColorThree"></div>
                    </div>
                    <div id="legendFour">
                        <p class="legendP">Very many<br>40-52</p>
                        <div id="legendColorFour"></div>
                    </div>
                </div>
                <div id="thirdViz"></div>
                <h3 class="category" id="cityReachText">City Reach & Frequency</h3>
                <p class="description">This bar chart visualizes how active each manager has been in different cities.
                    By selecting a city from the dropdown menu, you can compare how many gigs each manager has successfully arranged there. The chart offers a quick way to identify which managers have the strongest presence in specific locations.</p>
                <div id="fourthContainer">
                    <div id="fourthViz"></div>
                    <div id="dropDownContainer"></div>
                </div>
            </div>
            <div id="footer">
                <p id="footerText">We hope the visualizations have provided valuable insights into each manager’s performance. Whether you're analyzing trends or identifying standout managers, we’re glad to have supported your exploration.</p>
                <div id="footerBox">
                    <img id="footerPic" src="./media/images/raveimage.png">
                    <p id="igText">@RaveLinq</p>
                </div>
            </div>
        </div>
    </div>
    `;
    renderIncomeBarViz();
    renderIncomeLineViz();
    renderActivityViz();
    renderGeoReachViz();
}