function renderGUI () {
    let wrapper = document.getElementById("wrapper");
    wrapper.innerHTML = `
    <div id="backgroundContainer">
        <h1 id="titleText">RAVE LINQ</h1>
        <div id="contentContainer">
            <div id="infoBox">
                <h2>ARE YOU A DJ?</h2>
                <img id="ravePic" src="./media/images/ravePic.png">
                <p id="descriptionP">Here you can explore managers through powerful data visualizations that show exactly how they perform when it comes to income, audience demographics and where their artists are performing. Compare managers based on what matters most to you, and find the right fit with clarity and confidence.</p>
            </div>
            <div id="dividerBox">CONTINUE TO COMPARE MANAGERS</div>
            <div id="visualizationContainer">
                <h3 class="category">DJ Income Overview</h3>
                <p class="description">See the average yearly income generated by each manager’s DJs, adjusted for both the number of DJs they manage and how long they’ve been active.
                The result shows how much income, on average, each DJ under a manager brings in per year.</p>
                <div id="firstViz"></div>
                <p class="description" id="belowText">This line chart displays the average yearly income of DJs represented by various managers between 2015 and 2024. Each line corresponds to a different manager, showing income trends over time. Use the filter functionality to highlight one or more managers and compare how their DJs’ average incomes have evolved throughout the years.</p>
                <div id="secondViz"></div>
                <h3 class="category">Annual Gig Distribution</h3>
                <p class="description">Explore how active each manager has been in securing gigs for their DJs over the years. This heatmap uses color to reflect intensity: vibrant green signals high activity, vibrant pink indicates low activity, while lighter shades show moderate levels. Hover over a cell to see the average number of gigs per DJ for that year.</p>
                 <div id="legendBox">
                    <div id="legendOne">
                        <p class="legendP">Very few<br>0-13</p>
                        <div id="legendColorOne"></div>
                    </div>
                    <div id="legendTwo">
                        <p class="legendP">Few<br>14-26</p>
                        <div id="legendColorTwo"></div>
                    </div>
                    <div id="legendThree">
                        <p class="legendP">Many<br>15-39</p>
                        <div id="legendColorThree"></div>
                    </div>
                    <div id="legendFour">
                        <p class="legendP">Very many<br>40-52</p>
                        <div id="legendColorFour"></div>
                    </div>
                </div>
                <div id="thirdViz"></div>
                <h3 class="category">City Reach & Frequency</h3>
                <p class="description">This bubble chart shows how many unique cities each manager has booked gigs in and the average crowd size at those gigs. The size of each bubble represents how many DJs the manager works with, while color distinguishes each manager. Curious about a specific city? Use the dropdown to filter and see how many gigs each manager has secured there — and what the average attendance looked like.</p>
                <div id="fourthViz"></div>
            </div>
            <div id="footer"></div>
        </div>
    </div>
    `;
}